#!/usr/bin/perl

=head1 NAME

check-loadavg - Plugin to check the load average.

=head1 SYNOPSIS

    check-loadavg [ OPTIONS ]

    check-loadavg --help

=head1 REPORTING BUGS

Please report all bugs to <support(at)bloonix.de>.

=head1 AUTHOR

Jonny Schulz <support(at)bloonix.de>.

=head1 POWERED BY

     _    __ _____ _____ __  __ __ __   __
    | |__|  |     |     |  \|  |__|\  \/  /
    |  . |  |  |  |  |  |      |  | >    <
    |____|__|_____|_____|__|\__|__|/__/\__\

=head1 COPYRIGHT

Copyright (C) 2009-2014 by Jonny Schulz. All rights reserved.

=cut

use strict;
use warnings;
use Bloonix::Plugin;

# --------------------------------------------------
# Plugin options
# --------------------------------------------------

my $plugin = Bloonix::Plugin->new(version => "0.6");

$plugin->has_threshold(
    keys => [qw(avg1 avg5 avg15)]
);

$plugin->example(
    description => [
        "An example to check the load average and trigger",
        "",
        "- a warning if avg1 or avg5 is equal or higher than 20",
        "- a critical if avg1 or avg5 is equal or higher than 50"
    ],
    arguments => [
        warning => "avg1:ge:20",
        critical => "avg1:ge:50",
        warning => "avg5:ge:20",
        critical => "avg5:ge:50"
    ]
);

# --------------------------------------------------
# Parse options
# --------------------------------------------------

my $opt = $plugin->parse_options;

# --------------------------------------------------
# Load loadavg
# --------------------------------------------------

my $stat = { };

open my $fh, '<', "/proc/loadavg" or die "cannot open /proc/loadavg - $!";
($stat->{avg1}, $stat->{avg5}, $stat->{avg15}) = (split /\s+/, <$fh>)[0..2];
close $fh;

# --------------------------------------------------
# Check warning and critical
# --------------------------------------------------

my $result = $plugin->check_thresholds(
    stats => $stat,
    upshot_keys => [qw(avg1 avg5 avg15)]
);

$plugin->exit(
    status => $result->{status},
    message => $result->{upshot},
    stats => $stat
);
