Document: bloonix-plugins-linux
Title: Debian bloonix-plugins-linux Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-linux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-linux/bloonix-plugins-linux.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-linux/bloonix-plugins-linux.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-linux/bloonix-plugins-linux.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-linux/html/index.html
Files: /usr/share/doc/bloonix-plugins-linux/html/*.html


