#!/bin/sh

if [ ! -e "/etc/bloonix/agent/sudoers.d" ] ; then
    mkdir -p /etc/bloonix/agent/sudoers.d
    chown root:root /etc/bloonix/agent/sudoers.d
    chmod 755 /etc/bloonix/agent/sudoers.d
fi
for f in check-linux-updates check-lsi-raid check-mdadm check-service check-smart-health ; do
    if [ ! -e "/etc/bloonix/agent/sudoers.d/$f" ] ; then
        cp -a /usr/lib/bloonix/etc/sudoers.d/$f /etc/bloonix/agent/sudoers.d/
        chmod 440 /etc/bloonix/agent/sudoers.d/$f 
    fi
done

